### ISSUE TITLE
No items display in machine menu

### ISSUE THREAD

**Issue by trustedwizard** [nabi11/esx_food#1]
When opening a machine, the list of items does not display. The menu does display properly but there are no items in the list to choose from. 

![image](https://user-images.githubusercontent.com/25409166/41449470-41d7c9ca-702f-11e8-876f-d5292697d08a.png)

**Comment by Mew2cry** [comment]
did you run the SQL file in your db ?

**Comment by Mew2cry** [comment]
FIXED the issue, mising line in the SQL file.
